# Generated by Django 4.2.16 on 2024-11-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroidentificacion', models.CharField(max_length=20, unique=True)),
                ('primerapellido', models.CharField(max_length=50)),
                ('segundoapellido', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('correoelectronico', models.EmailField(max_length=50, unique=True)),
            ],
        ),
    ]
