# Generated by Django 4.2.16 on 2024-10-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
    ]
