# Generated by Django 5.1.1 on 2024-11-16 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('horario', '0002_auto_20241030_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='fecha',
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AddField(
            model_name='horario',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='salon',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
