# Generated by Django 4.2.16 on 2024-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroidentificacion', models.CharField(max_length=20, unique=True)),
                ('primerapellido', models.CharField(max_length=50)),
                ('segundoapellido', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('fechanacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('ciudadresidencia', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, null=True)),
                ('ciudadnacimiento', models.CharField(max_length=50)),
                ('correoelectronico', models.EmailField(max_length=50, unique=True)),
                ('carreraestudiando', models.CharField(max_length=100)),
                ('nivelacademico', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
    ]
